const ADD_ITEM_SUCCESS = '[menu] ADD_ITEM_SUCCESS';
const DELETE_ITEM_SUCCESS = '[menu] DELETE_ITEM_SUCCESS';
const CHANGE_FILTER = '[menu] CHANGE_FILTER';
const FETCH_CATEGORIES_SUCCESS = '[menu] FETCH_CATEGORIES_SUCCESS';

const FETCH_REQUEST = '[menu] FETCH_REQUEST';
const FETCH_SUCCESS = '[menu] FETCH_SUCCESS';
const FETCH_ERROR = '[menu] FETCH_ERROR';

export default {
  FETCH_CATEGORIES_SUCCESS,
  ADD_ITEM_SUCCESS,
  DELETE_ITEM_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
